#!/usr/bin/env bash
# Generates /etc/nginx/sites-include/on-demand.conf from products.yml.
#
# For every product that declares `public_paths`, emits:
#   * bare redirects  (location = /pledge  -> 301 /pledge/)
#   * proxy blocks    (location /pledge/  -> upstream, X-Forwarded-Prefix, mirror)
#   * a mirror target (location = /_nc_touch_<slug>) hitting the runtime manager
#   * if policy == on_demand: cold-start error_page + a readiness probe
#                                 (location = /_nc_probe/<slug>) that self-heals
# The shared /_nc_loading block (the branded loader) is emitted exactly once.
#
# Idempotent and safe to re-run from install-nginx.sh / deploy-all.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROD_DEBIAN_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

require_cmd python3
nc_ensure_yaml

OUT_DIR="${OUT_DIR:-/etc/nginx/sites-include}"
OUT_FILE="${OUT_DIR}/on-demand.conf"
LOADER_SRC="${PROD_DEBIAN_DIR}/nginx/loaders/on-demand.html"
LOADER_DST_DIR="${LOADER_DST_DIR:-/runtime/nightcraft/loaders}"
LOADER_DST="${LOADER_DST_DIR}/on-demand.html"

ensure_dir "${OUT_DIR}"
ensure_dir "${LOADER_DST_DIR}"

# Deploy the shared loader page (owned by root; served by nginx).
install -m 0644 "${LOADER_SRC}" "${LOADER_DST}"

MANAGER_UPSTREAM="nightcraft_runtime_manager_upstream"

{
  echo "# Generated by gen-nginx-on-demand.sh — DO NOT EDIT BY HAND."
  echo "# Source of truth: products.yml"
  echo

  emitted_loading=0

  while IFS= read -r slug; do
    [[ -z "${slug}" ]] && continue

    policy="$(nc_policy "${slug}")"
    upstream="$(nc_upstream "${slug}")"
    # read public paths into an array
    mapfile -t paths < <(nc_public_paths "${slug}")

    [[ "${#paths[@]}" -eq 0 ]] && continue

    echo "# --- ${slug} (${policy}) ---"
    echo

    # Mirror target: touch the runtime manager (starts the service on first hit).
    echo "location = /_nc_touch_${slug} {"
    echo "    internal;"
    echo "    proxy_pass http://${MANAGER_UPSTREAM}/touch/${slug};"
    echo "    proxy_set_header Host \$host;"
    echo "    proxy_set_header X-Real-IP \$remote_addr;"
    echo "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
    echo "    proxy_set_header X-Forwarded-Proto \$scheme;"
    echo "}"
    echo

    if [[ "${policy}" == "on_demand" ]]; then
      # Readiness probe: also mirrors (self-heals the start) and does NOT
      # intercept errors, so a still-down service returns 502 to the JS checker.
      echo "location = /_nc_probe/${slug} {"
      echo "    proxy_pass http://${upstream}/;"
      echo "    proxy_http_version 1.1;"
      echo "    proxy_set_header Host \$host;"
      echo "    proxy_set_header X-Real-IP \$remote_addr;"
      echo "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
      echo "    proxy_set_header X-Forwarded-Proto \$scheme;"
      echo "    proxy_set_header Connection \"\";"
      echo "    proxy_intercept_errors off;"
      echo "    mirror /_nc_touch_${slug};"
      echo "}"
      echo

      # Start-status probe: reports whether the manager succeeded/failed to
      # start the service, so the loader can stop spinning forever on a crash.
      echo "location = /_nc_status/${slug} {"
      echo "    proxy_pass http://${MANAGER_UPSTREAM}/status/${slug};"
      echo "    proxy_set_header Host \$host;"
      echo "    proxy_set_header X-Real-IP \$remote_addr;"
      echo "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
      echo "    proxy_set_header X-Forwarded-Proto \$scheme;"
      echo "}"
      echo

      # Cold-start handler: redirect to the branded loading page.
      # `next` is the LAST query param and may itself contain ?/&, so the loader
      # parses it as the trailing value (no URL-encoding needed).
      echo "location @nc_cold_${slug} {"
      echo "    return 302 /_nc_loading?slug=${slug}&next=\$request_uri;"
      echo "}"
      echo
    fi

    # Bare redirects + proxy blocks for each public path.
    for path in "${paths[@]}"; do
      echo "location = ${path} {"
      echo "    return 301 ${path}/;"
      echo "}"
      echo

      echo "location ${path}/ {"
      echo "    proxy_pass http://${upstream}/;"
      echo "    proxy_http_version 1.1;"
      echo "    proxy_set_header Host \$host;"
      echo "    proxy_set_header X-Real-IP \$remote_addr;"
      echo "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
      echo "    proxy_set_header X-Forwarded-Proto \$scheme;"
      echo "    proxy_set_header X-Forwarded-Prefix ${path};"
      echo "    proxy_set_header Connection \"\";"
      echo "    proxy_read_timeout 120;"
      echo "    proxy_connect_timeout 30;"
      echo "    mirror /_nc_touch_${slug};"
      if [[ "${policy}" == "on_demand" ]]; then
        echo "    proxy_intercept_errors on;"
        echo "    error_page 502 503 504 = @nc_cold_${slug};"
      fi
      echo "}"
      echo
    done

    # The shared loader block is emitted exactly once, globally.
    if [[ "${emitted_loading}" -eq 0 ]]; then
      echo "# Shared branded loading page (served for every on_demand product)."
      echo "location = /_nc_loading {"
      echo "    default_type text/html;"
      echo "    alias ${LOADER_DST};"
      echo "}"
      echo
      emitted_loading=1
    fi
  done < <(nc_slugs)
} > "${OUT_FILE}"

log "Wrote ${OUT_FILE} ($(grep -c '^location' "${OUT_FILE}") location blocks)"
