CATALOG_SEED_DATA = [
    {
        "common": {
            "category": "book",
            "title": "The Hobbit",
            "creator_display_name": "J.R.R. Tolkien",
            "image_url": "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
            "description": "Bilbo Baggins is drawn into an unexpected adventure involving dwarves, dragons, and hidden treasure.",
            "source_type": "openlibrary",
            "source_id": "9780547928227",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "author": "J.R.R. Tolkien",
            "year": 1937,
            "pages": 310,
            "publisher": "George Allen & Unwin",
            "isbn": "9780547928227",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "Dune",
            "creator_display_name": "Frank Herbert",
            "image_url": "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
            "description": "Paul Atreides becomes embroiled in a struggle for power on the desert planet Arrakis.",
            "source_type": "openlibrary",
            "source_id": "9780441172719",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "author": "Frank Herbert",
            "year": 1965,
            "pages": 688,
            "publisher": "Chilton Books",
            "isbn": "9780441172719",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "1984",
            "creator_display_name": "George Orwell",
            "image_url": "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
            "description": "A chilling portrayal of a totalitarian state built on surveillance, censorship, and control.",
            "source_type": "openlibrary",
            "source_id": "9780451524935",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "author": "George Orwell",
            "year": 1949,
            "pages": 328,
            "publisher": "Secker & Warburg",
            "isbn": "9780451524935",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "Pride and Prejudice",
            "creator_display_name": "Jane Austen",
            "image_url": "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
            "description": "Elizabeth Bennet navigates social expectations, family pressures, and an evolving relationship with Mr. Darcy.",
            "source_type": "openlibrary",
            "source_id": "9780141439518",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "author": "Jane Austen",
            "year": 1813,
            "pages": 432,
            "publisher": "T. Egerton",
            "isbn": "9780141439518",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "The Name of the Wind",
            "creator_display_name": "Patrick Rothfuss",
            "image_url": "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg",
            "description": "Kvothe recounts his extraordinary life story, from gifted child to legendary figure.",
            "source_type": "openlibrary",
            "source_id": "9780756404741",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "author": "Patrick Rothfuss",
            "year": 2007,
            "pages": 662,
            "publisher": "DAW Books",
            "isbn": "9780756404741",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "Spirited Away",
            "creator_display_name": "Hayao Miyazaki",
            "image_url": "spirited-away-poster.jpg",
            "description": "A young girl enters a mysterious spirit world.",
            "source_type": "tmdb",
            "source_id": "129",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "director": "Hayao Miyazaki",
            "year": 2001,
            "runtime_minutes": 125,
            "country": "Japan",
            "language": "Japanese",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "The Shawshank Redemption",
            "creator_display_name": "Frank Darabont",
            "image_url": "shawshank-poster.jpg",
            "description": "Friendship and hope inside a prison.",
            "source_type": "tmdb",
            "source_id": "278",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "director": "Frank Darabont",
            "year": 1994,
            "runtime_minutes": 142,
            "country": "USA",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "Parasite",
            "creator_display_name": "Bong Joon-ho",
            "image_url": "parasite-poster.jpg",
            "description": "A poor family infiltrates a wealthy household.",
            "source_type": "tmdb",
            "source_id": "496243",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "director": "Bong Joon-ho",
            "year": 2019,
            "runtime_minutes": 132,
            "country": "South Korea",
            "language": "Korean",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "Interstellar",
            "creator_display_name": "Christopher Nolan",
            "image_url": "interstellar-poster.jpg",
            "description": "A journey through space to save humanity.",
            "source_type": "tmdb",
            "source_id": "157336",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "director": "Christopher Nolan",
            "year": 2014,
            "runtime_minutes": 169,
            "country": "USA",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "The Godfather",
            "creator_display_name": "Francis Ford Coppola",
            "image_url": "godfather-poster.jpg",
            "description": "The rise of a powerful mafia family.",
            "source_type": "tmdb",
            "source_id": "238",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "director": "Francis Ford Coppola",
            "year": 1972,
            "runtime_minutes": 175,
            "country": "USA",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Bohemian Rhapsody",
            "creator_display_name": "Queen",
            "image_url": "night-at-the-opera.jpg",
            "description": "One of rock's most iconic songs.",
            "source_type": "musicbrainz",
            "source_id": "song-001",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Queen",
            "album": "A Night at the Opera",
            "year": 1975,
            "duration_seconds": 354,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Imagine",
            "creator_display_name": "John Lennon",
            "image_url": "imagine.jpg",
            "description": "A song envisioning a peaceful world.",
            "source_type": "musicbrainz",
            "source_id": "song-002",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "John Lennon",
            "album": "Imagine",
            "year": 1971,
            "duration_seconds": 183,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Hallelujah",
            "creator_display_name": "Leonard Cohen",
            "image_url": "hallelujah.jpg",
            "description": "A poetic and spiritual classic.",
            "source_type": "musicbrainz",
            "source_id": "song-003",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Leonard Cohen",
            "album": "Various Positions",
            "year": 1984,
            "duration_seconds": 282,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Lose Yourself",
            "creator_display_name": "Eminem",
            "image_url": "8-mile.jpg",
            "description": "An anthem of determination.",
            "source_type": "musicbrainz",
            "source_id": "song-004",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Eminem",
            "album": "8 Mile Soundtrack",
            "year": 2002,
            "duration_seconds": 326,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Someone Like You",
            "creator_display_name": "Adele",
            "image_url": "21.jpg",
            "description": "A powerful ballad about heartbreak.",
            "source_type": "musicbrainz",
            "source_id": "song-005",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Adele",
            "album": "21",
            "year": 2011,
            "duration_seconds": 285,
        },
    },
    {
        "common": {
            "category": "art",
            "title": "The Starry Night",
            "creator_display_name": "Vincent van Gogh",
            "image_url": "starry-night.jpg",
            "description": "A swirling depiction of the night sky.",
            "source_type": "metmuseum",
            "source_id": "art-001",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Vincent van Gogh",
            "year": 1889,
            "medium": "Oil on Canvas",
            "movement": "Post-Impressionism",
            "museum": "Museum of Modern Art",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "Mona Lisa",
            "creator_display_name": "Leonardo da Vinci",
            "image_url": "mona-lisa.jpg",
            "description": "The world's most famous portrait.",
            "source_type": "metmuseum",
            "source_id": "art-002",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Leonardo da Vinci",
            "year": 1503,
            "medium": "Oil on Wood",
            "movement": "Renaissance",
            "museum": "Louvre Museum",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "The Persistence of Memory",
            "creator_display_name": "Salvador Dali",
            "image_url": "memory.jpg",
            "description": "The famous melting clocks painting.",
            "source_type": "metmuseum",
            "source_id": "art-003",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Salvador Dali",
            "year": 1931,
            "medium": "Oil on Canvas",
            "movement": "Surrealism",
            "museum": "MoMA",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "The Scream",
            "creator_display_name": "Edvard Munch",
            "image_url": "the-scream.jpg",
            "description": "An iconic image of anxiety.",
            "source_type": "metmuseum",
            "source_id": "art-004",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Edvard Munch",
            "year": 1893,
            "medium": "Oil, Tempera and Pastel",
            "movement": "Expressionism",
            "museum": "National Museum of Norway",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "Girl with a Pearl Earring",
            "creator_display_name": "Johannes Vermeer",
            "image_url": "pearl-earring.jpg",
            "description": "One of history's most recognizable portraits.",
            "source_type": "metmuseum",
            "source_id": "art-005",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Johannes Vermeer",
            "year": 1665,
            "medium": "Oil on Canvas",
            "movement": "Dutch Golden Age",
            "museum": "Mauritshuis",
        },
    },
]
