CATALOG_SEED_DATA = [
    {
        "common": {
            "category": "book",
            "title": "The Hobbit",
            "creator_display_name": "J.R.R. Tolkien",
            "image_url": "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
            "description": "Bilbo Baggins is drawn into an unexpected adventure involving dwarves, dragons, and hidden treasure.",
            "source_type": "openlibrary",
            "source_id": "9780547928227",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "author": "J.R.R. Tolkien",
            "year": 1937,
            "pages": 310,
            "publisher": "George Allen & Unwin",
            "isbn": "9780547928227",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "Dune",
            "creator_display_name": "Frank Herbert",
            "image_url": "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
            "description": "Paul Atreides becomes embroiled in a struggle for power on the desert planet Arrakis.",
            "source_type": "openlibrary",
            "source_id": "9780441172719",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "author": "Frank Herbert",
            "year": 1965,
            "pages": 688,
            "publisher": "Chilton Books",
            "isbn": "9780441172719",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "1984",
            "creator_display_name": "George Orwell",
            "image_url": "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
            "description": "A chilling portrayal of a totalitarian state built on surveillance, censorship, and control.",
            "source_type": "openlibrary",
            "source_id": "9780451524935",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "author": "George Orwell",
            "year": 1949,
            "pages": 328,
            "publisher": "Secker & Warburg",
            "isbn": "9780451524935",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "Pride and Prejudice",
            "creator_display_name": "Jane Austen",
            "image_url": "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
            "description": "Elizabeth Bennet navigates social expectations, family pressures, and an evolving relationship with Mr. Darcy.",
            "source_type": "openlibrary",
            "source_id": "9780141439518",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "author": "Jane Austen",
            "year": 1813,
            "pages": 432,
            "publisher": "T. Egerton",
            "isbn": "9780141439518",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "The Name of the Wind",
            "creator_display_name": "Patrick Rothfuss",
            "image_url": "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg",
            "description": "Kvothe recounts his extraordinary life story, from gifted child to legendary figure.",
            "source_type": "openlibrary",
            "source_id": "9780756404741",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "author": "Patrick Rothfuss",
            "year": 2007,
            "pages": 662,
            "publisher": "DAW Books",
            "isbn": "9780756404741",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "Spirited Away",
            "creator_display_name": "Hayao Miyazaki",
            "image_url": "spirited-away-poster.jpg",
            "description": "A young girl enters a mysterious spirit world.",
            "source_type": "tmdb",
            "source_id": "129",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "director": "Hayao Miyazaki",
            "year": 2001,
            "runtime_minutes": 125,
            "country": "Japan",
            "language": "Japanese",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "The Shawshank Redemption",
            "creator_display_name": "Frank Darabont",
            "image_url": "shawshank-poster.jpg",
            "description": "Friendship and hope inside a prison.",
            "source_type": "tmdb",
            "source_id": "278",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "director": "Frank Darabont",
            "year": 1994,
            "runtime_minutes": 142,
            "country": "USA",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "Parasite",
            "creator_display_name": "Bong Joon-ho",
            "image_url": "parasite-poster.jpg",
            "description": "A poor family infiltrates a wealthy household.",
            "source_type": "tmdb",
            "source_id": "496243",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "director": "Bong Joon-ho",
            "year": 2019,
            "runtime_minutes": 132,
            "country": "South Korea",
            "language": "Korean",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "Interstellar",
            "creator_display_name": "Christopher Nolan",
            "image_url": "interstellar-poster.jpg",
            "description": "A journey through space to save humanity.",
            "source_type": "tmdb",
            "source_id": "157336",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "director": "Christopher Nolan",
            "year": 2014,
            "runtime_minutes": 169,
            "country": "USA",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "The Godfather",
            "creator_display_name": "Francis Ford Coppola",
            "image_url": "godfather-poster.jpg",
            "description": "The rise of a powerful mafia family.",
            "source_type": "tmdb",
            "source_id": "238",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "director": "Francis Ford Coppola",
            "year": 1972,
            "runtime_minutes": 175,
            "country": "USA",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Bohemian Rhapsody",
            "creator_display_name": "Queen",
            "image_url": "night-at-the-opera.jpg",
            "description": "One of rock's most iconic songs.",
            "source_type": "musicbrainz",
            "source_id": "song-001",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Queen",
            "album": "A Night at the Opera",
            "year": 1975,
            "duration_seconds": 354,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Imagine",
            "creator_display_name": "John Lennon",
            "image_url": "imagine.jpg",
            "description": "A song envisioning a peaceful world.",
            "source_type": "musicbrainz",
            "source_id": "song-002",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "John Lennon",
            "album": "Imagine",
            "year": 1971,
            "duration_seconds": 183,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Hallelujah",
            "creator_display_name": "Leonard Cohen",
            "image_url": "hallelujah.jpg",
            "description": "A poetic and spiritual classic.",
            "source_type": "musicbrainz",
            "source_id": "song-003",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Leonard Cohen",
            "album": "Various Positions",
            "year": 1984,
            "duration_seconds": 282,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Lose Yourself",
            "creator_display_name": "Eminem",
            "image_url": "8-mile.jpg",
            "description": "An anthem of determination.",
            "source_type": "musicbrainz",
            "source_id": "song-004",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Eminem",
            "album": "8 Mile Soundtrack",
            "year": 2002,
            "duration_seconds": 326,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Someone Like You",
            "creator_display_name": "Adele",
            "image_url": "21.jpg",
            "description": "A powerful ballad about heartbreak.",
            "source_type": "musicbrainz",
            "source_id": "song-005",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Adele",
            "album": "21",
            "year": 2011,
            "duration_seconds": 285,
        },
    },
    {
        "common": {
            "category": "art",
            "title": "The Starry Night",
            "creator_display_name": "Vincent van Gogh",
            "image_url": "starry-night.jpg",
            "description": "A swirling depiction of the night sky.",
            "source_type": "metmuseum",
            "source_id": "art-001",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Vincent van Gogh",
            "year": 1889,
            "medium": "Oil on Canvas",
            "movement": "Post-Impressionism",
            "museum": "Museum of Modern Art",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "Mona Lisa",
            "creator_display_name": "Leonardo da Vinci",
            "image_url": "mona-lisa.jpg",
            "description": "The world's most famous portrait.",
            "source_type": "metmuseum",
            "source_id": "art-002",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Leonardo da Vinci",
            "year": 1503,
            "medium": "Oil on Wood",
            "movement": "Renaissance",
            "museum": "Louvre Museum",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "The Persistence of Memory",
            "creator_display_name": "Salvador Dali",
            "image_url": "memory.jpg",
            "description": "The famous melting clocks painting.",
            "source_type": "metmuseum",
            "source_id": "art-003",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Salvador Dali",
            "year": 1931,
            "medium": "Oil on Canvas",
            "movement": "Surrealism",
            "museum": "MoMA",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "The Scream",
            "creator_display_name": "Edvard Munch",
            "image_url": "the-scream.jpg",
            "description": "An iconic image of anxiety.",
            "source_type": "metmuseum",
            "source_id": "art-004",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Edvard Munch",
            "year": 1893,
            "medium": "Oil, Tempera and Pastel",
            "movement": "Expressionism",
            "museum": "National Museum of Norway",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "Girl with a Pearl Earring",
            "creator_display_name": "Johannes Vermeer",
            "image_url": "pearl-earring.jpg",
            "description": "One of history's most recognizable portraits.",
            "source_type": "metmuseum",
            "source_id": "art-005",
            "is_user_submitted": False,
            "metadata_confidence": 1.0,
        },
        "metadata": {
            "artist": "Johannes Vermeer",
            "year": 1665,
            "medium": "Oil on Canvas",
            "movement": "Dutch Golden Age",
            "museum": "Mauritshuis",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "One Hundred Years of Solitude",
            "creator_display_name": "Gabriel García Márquez",
            "image_url": "",
            "description": "A landmark magical realist novel tracing the Buendía family and the mythical town of Macondo.",
            "source_type": "manual",
            "source_id": "book_one_hundred_years_of_solitude",
            "is_user_submitted": False,
            "metadata_confidence": 0.95,
        },
        "metadata": {
            "author": "Gabriel García Márquez",
            "year": 1967,
            "pages": 417,
            "publisher": "Editorial Sudamericana",
            "isbn": "",
            "language": "Spanish",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "Invisible Cities",
            "creator_display_name": "Italo Calvino",
            "image_url": "",
            "description": "A poetic, fragmented novel where Marco Polo describes imaginary cities to Kublai Khan.",
            "source_type": "manual",
            "source_id": "book_invisible_cities",
            "is_user_submitted": False,
            "metadata_confidence": 0.9,
        },
        "metadata": {
            "author": "Italo Calvino",
            "year": 1972,
            "pages": 165,
            "publisher": "Einaudi",
            "isbn": "",
            "language": "Italian",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "The Left Hand of Darkness",
            "creator_display_name": "Ursula K. Le Guin",
            "image_url": "",
            "description": "A science fiction classic exploring gender, politics, anthropology, and alien society.",
            "source_type": "manual",
            "source_id": "book_left_hand_of_darkness",
            "is_user_submitted": False,
            "metadata_confidence": 0.95,
        },
        "metadata": {
            "author": "Ursula K. Le Guin",
            "year": 1969,
            "pages": 304,
            "publisher": "Ace Books",
            "isbn": "",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "Stalker",
            "creator_display_name": "Andrei Tarkovsky",
            "image_url": "",
            "description": "A philosophical science fiction film about a journey into a mysterious forbidden zone.",
            "source_type": "manual",
            "source_id": "film_stalker",
            "is_user_submitted": False,
            "metadata_confidence": 0.95,
        },
        "metadata": {
            "director": "Andrei Tarkovsky",
            "year": 1979,
            "runtime_minutes": 163,
            "country": "Soviet Union",
            "language": "Russian",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "In the Mood for Love",
            "creator_display_name": "Wong Kar-wai",
            "image_url": "",
            "description": "A visually restrained romantic drama about longing, memory, and missed connection.",
            "source_type": "manual",
            "source_id": "film_in_the_mood_for_love",
            "is_user_submitted": False,
            "metadata_confidence": 0.95,
        },
        "metadata": {
            "director": "Wong Kar-wai",
            "year": 2000,
            "runtime_minutes": 98,
            "country": "Hong Kong",
            "language": "Cantonese",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "Pather Panchali",
            "creator_display_name": "Satyajit Ray",
            "image_url": "",
            "description": "A foundational work of Indian parallel cinema, centered on childhood, poverty, and rural Bengal.",
            "source_type": "manual",
            "source_id": "film_pather_panchali",
            "is_user_submitted": False,
            "metadata_confidence": 0.95,
        },
        "metadata": {
            "director": "Satyajit Ray",
            "year": 1955,
            "runtime_minutes": 125,
            "country": "India",
            "language": "Bengali",
        },
    },
    {
        "common": {
            "category": "song",
            "title": "A Day in the Life",
            "creator_display_name": "The Beatles",
            "image_url": "",
            "description": "A studio-era landmark blending pop songwriting, orchestral experimentation, and surreal observation.",
            "source_type": "manual",
            "source_id": "song_a_day_in_the_life",
            "is_user_submitted": False,
            "metadata_confidence": 0.95,
        },
        "metadata": {
            "artist": "The Beatles",
            "album": "Sgt. Pepper's Lonely Hearts Club Band",
            "year": 1967,
            "duration_seconds": 337,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Breathe",
            "creator_display_name": "Pink Floyd",
            "image_url": "",
            "description": "A spacious progressive rock track exploring time, pressure, and modern life.",
            "source_type": "manual",
            "source_id": "song_breathe_pink_floyd",
            "is_user_submitted": False,
            "metadata_confidence": 0.9,
        },
        "metadata": {
            "artist": "Pink Floyd",
            "album": "The Dark Side of the Moon",
            "year": 1973,
            "duration_seconds": 163,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Joga",
            "creator_display_name": "Björk",
            "image_url": "",
            "description": "An orchestral electronic song connecting emotional landscapes with Icelandic geography.",
            "source_type": "manual",
            "source_id": "song_joga",
            "is_user_submitted": False,
            "metadata_confidence": 0.9,
        },
        "metadata": {
            "artist": "Björk",
            "album": "Homogenic",
            "year": 1997,
            "duration_seconds": 300,
        },
    },
    {
        "common": {
            "category": "art",
            "title": "The Persistence of Memory",
            "creator_display_name": "Salvador Dalí",
            "image_url": "",
            "description": "A surrealist painting famous for its melting clocks and dreamlike treatment of time.",
            "source_type": "manual",
            "source_id": "art_persistence_of_memory",
            "is_user_submitted": False,
            "metadata_confidence": 0.95,
        },
        "metadata": {
            "artist": "Salvador Dalí",
            "year": 1931,
            "medium": "Oil on canvas",
            "movement": "Surrealism",
            "museum": "Museum of Modern Art, New York",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "The Great Wave off Kanagawa",
            "creator_display_name": "Katsushika Hokusai",
            "image_url": "",
            "description": "A Japanese ukiyo-e woodblock print depicting a towering wave near Mount Fuji.",
            "source_type": "manual",
            "source_id": "art_great_wave_off_kanagawa",
            "is_user_submitted": False,
            "metadata_confidence": 0.95,
        },
        "metadata": {
            "artist": "Katsushika Hokusai",
            "year": 1831,
            "medium": "Woodblock print",
            "movement": "Ukiyo-e",
            "museum": "Multiple collections",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "Guernica",
            "creator_display_name": "Pablo Picasso",
            "image_url": "",
            "description": "A monumental anti-war painting responding to the bombing of Guernica during the Spanish Civil War.",
            "source_type": "manual",
            "source_id": "art_guernica",
            "is_user_submitted": False,
            "metadata_confidence": 0.95,
        },
        "metadata": {
            "artist": "Pablo Picasso",
            "year": 1937,
            "medium": "Oil on canvas",
            "movement": "Cubism",
            "museum": "Museo Reina Sofía, Madrid",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "The Odyssey",
            "creator_display_name": "Homer",
            "image_url": "",
            "description": "An epic poem following Odysseus' long journey home after the Trojan War. A foundational work of Western storytelling.",
            "source_type": "manual",
            "source_id": "book_odyssey",
            "is_user_submitted": False,
            "metadata_confidence": 0.98,
        },
        "metadata": {
            "author": "Homer",
            "year": -700,
            "pages": 541,
            "publisher": "",
            "isbn": "",
            "language": "Ancient Greek",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "The Divine Comedy",
            "creator_display_name": "Dante Alighieri",
            "image_url": "",
            "description": "A journey through Hell, Purgatory, and Paradise that shaped centuries of literature, theology, and art.",
            "source_type": "manual",
            "source_id": "book_divine_comedy",
            "is_user_submitted": False,
            "metadata_confidence": 0.98,
        },
        "metadata": {
            "author": "Dante Alighieri",
            "year": 1321,
            "pages": 798,
            "publisher": "",
            "isbn": "",
            "language": "Italian",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "Don Quixote",
            "creator_display_name": "Miguel de Cervantes",
            "image_url": "",
            "description": "A satire of chivalric romance often considered the first modern novel.",
            "source_type": "manual",
            "source_id": "book_don_quixote",
            "is_user_submitted": False,
            "metadata_confidence": 0.98,
        },
        "metadata": {
            "author": "Miguel de Cervantes",
            "year": 1605,
            "pages": 863,
            "publisher": "",
            "isbn": "",
            "language": "Spanish",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "The Seventh Seal",
            "creator_display_name": "Ingmar Bergman",
            "image_url": "",
            "description": "A knight returning from the Crusades confronts death in one of cinema's defining philosophical works.",
            "source_type": "manual",
            "source_id": "film_seventh_seal",
            "is_user_submitted": False,
            "metadata_confidence": 0.97,
        },
        "metadata": {
            "director": "Ingmar Bergman",
            "year": 1957,
            "runtime_minutes": 96,
            "country": "Sweden",
            "language": "Swedish",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "8½",
            "creator_display_name": "Federico Fellini",
            "image_url": "",
            "description": "A surreal exploration of creativity and artistic paralysis that influenced generations of filmmakers.",
            "source_type": "manual",
            "source_id": "film_8_half",
            "is_user_submitted": False,
            "metadata_confidence": 0.97,
        },
        "metadata": {
            "director": "Federico Fellini",
            "year": 1963,
            "runtime_minutes": 138,
            "country": "Italy",
            "language": "Italian",
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Symphony No. 5",
            "creator_display_name": "Ludwig van Beethoven",
            "image_url": "",
            "description": "Perhaps the most recognizable motif in classical music, symbolizing struggle and triumph.",
            "source_type": "manual",
            "source_id": "song_beethoven_5",
            "is_user_submitted": False,
            "metadata_confidence": 0.99,
        },
        "metadata": {
            "artist": "Ludwig van Beethoven",
            "album": "Symphony No. 5 in C Minor",
            "year": 1808,
            "duration_seconds": 2100,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "The Four Seasons: Spring",
            "creator_display_name": "Antonio Vivaldi",
            "image_url": "",
            "description": "One of the most influential and recognizable examples of program music.",
            "source_type": "manual",
            "source_id": "song_vivaldi_spring",
            "is_user_submitted": False,
            "metadata_confidence": 0.99,
        },
        "metadata": {
            "artist": "Antonio Vivaldi",
            "album": "The Four Seasons",
            "year": 1725,
            "duration_seconds": 620,
        },
    },
    {
        "common": {
            "category": "art",
            "title": "The School of Athens",
            "creator_display_name": "Raphael",
            "image_url": "",
            "description": "A Renaissance masterpiece depicting the great philosophers of antiquity.",
            "source_type": "manual",
            "source_id": "art_school_of_athens",
            "is_user_submitted": False,
            "metadata_confidence": 0.98,
        },
        "metadata": {
            "artist": "Raphael",
            "year": 1511,
            "medium": "Fresco",
            "movement": "High Renaissance",
            "museum": "Apostolic Palace, Vatican City",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "Las Meninas",
            "creator_display_name": "Diego Velázquez",
            "image_url": "",
            "description": "A revolutionary exploration of perspective, representation, and the act of looking.",
            "source_type": "manual",
            "source_id": "art_las_meninas",
            "is_user_submitted": False,
            "metadata_confidence": 0.98,
        },
        "metadata": {
            "artist": "Diego Velázquez",
            "year": 1656,
            "medium": "Oil on canvas",
            "movement": "Baroque",
            "museum": "Museo del Prado, Madrid",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "The Birth of Venus",
            "creator_display_name": "Sandro Botticelli",
            "image_url": "",
            "description": "One of the defining images of the Renaissance and classical mythology in art.",
            "source_type": "manual",
            "source_id": "art_birth_of_venus",
            "is_user_submitted": False,
            "metadata_confidence": 0.98,
        },
        "metadata": {
            "artist": "Sandro Botticelli",
            "year": 1485,
            "medium": "Tempera on canvas",
            "movement": "Early Renaissance",
            "museum": "Uffizi Gallery, Florence",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "The Autobiography of Malcolm X",
            "creator_display_name": "Malcolm X",
            "image_url": "",
            "description": "A powerful account of transformation, racial injustice, political awakening, and resistance in America.",
            "source_type": "manual",
            "source_id": "book_autobiography_malcolm_x",
            "is_user_submitted": False,
            "metadata_confidence": 0.98,
        },
        "metadata": {
            "author": "Malcolm X and Alex Haley",
            "year": 1965,
            "pages": 527,
            "publisher": "Grove Press",
            "isbn": "",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "Long Walk to Freedom",
            "creator_display_name": "Nelson Mandela",
            "image_url": "",
            "description": "The life story of Nelson Mandela and the struggle against apartheid in South Africa.",
            "source_type": "manual",
            "source_id": "book_long_walk_to_freedom",
            "is_user_submitted": False,
            "metadata_confidence": 0.98,
        },
        "metadata": {
            "author": "Nelson Mandela",
            "year": 1994,
            "pages": 656,
            "publisher": "Little, Brown and Company",
            "isbn": "",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "Bhagat Singh: Why I Am an Atheist",
            "creator_display_name": "Bhagat Singh",
            "image_url": "",
            "description": "A famous essay reflecting on reason, conviction, sacrifice, and revolutionary thought.",
            "source_type": "manual",
            "source_id": "book_why_i_am_an_atheist",
            "is_user_submitted": False,
            "metadata_confidence": 0.95,
        },
        "metadata": {
            "author": "Bhagat Singh",
            "year": 1930,
            "pages": 64,
            "publisher": "",
            "isbn": "",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "The Battle of Algiers",
            "creator_display_name": "Gillo Pontecorvo",
            "image_url": "",
            "description": "A landmark film depicting the Algerian struggle for independence from French colonial rule.",
            "source_type": "manual",
            "source_id": "film_battle_of_algiers",
            "is_user_submitted": False,
            "metadata_confidence": 0.99,
        },
        "metadata": {
            "director": "Gillo Pontecorvo",
            "year": 1966,
            "runtime_minutes": 121,
            "country": "Algeria / Italy",
            "language": "Arabic",
        },
    },
    {
        "common": {
            "category": "film",
            "title": "Gandhi",
            "creator_display_name": "Richard Attenborough",
            "image_url": "",
            "description": "An epic portrayal of Mahatma Gandhi and India's independence movement.",
            "source_type": "manual",
            "source_id": "film_gandhi",
            "is_user_submitted": False,
            "metadata_confidence": 0.98,
        },
        "metadata": {
            "director": "Richard Attenborough",
            "year": 1982,
            "runtime_minutes": 191,
            "country": "United Kingdom / India",
            "language": "English",
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Bella Ciao",
            "creator_display_name": "Italian Partisans",
            "image_url": "",
            "description": "A folk song that became an international anthem of anti-fascist resistance and freedom struggles.",
            "source_type": "manual",
            "source_id": "song_bella_ciao",
            "is_user_submitted": False,
            "metadata_confidence": 0.97,
        },
        "metadata": {
            "artist": "Traditional",
            "album": "Italian Resistance Songs",
            "year": 1944,
            "duration_seconds": 240,
        },
    },
    {
        "common": {
            "category": "song",
            "title": "Strange Fruit",
            "creator_display_name": "Billie Holiday",
            "image_url": "",
            "description": "A haunting protest song confronting racial violence and lynching in America.",
            "source_type": "manual",
            "source_id": "song_strange_fruit",
            "is_user_submitted": False,
            "metadata_confidence": 0.99,
        },
        "metadata": {
            "artist": "Billie Holiday",
            "album": "Strange Fruit",
            "year": 1939,
            "duration_seconds": 193,
        },
    },
    {
        "common": {
            "category": "art",
            "title": "Liberty Leading the People",
            "creator_display_name": "Eugène Delacroix",
            "image_url": "",
            "description": "An iconic painting commemorating the July Revolution and the pursuit of liberty.",
            "source_type": "manual",
            "source_id": "art_liberty_leading_people",
            "is_user_submitted": False,
            "metadata_confidence": 0.99,
        },
        "metadata": {
            "artist": "Eugène Delacroix",
            "year": 1830,
            "medium": "Oil on canvas",
            "movement": "Romanticism",
            "museum": "Louvre Museum, Paris",
        },
    },
    {
        "common": {
            "category": "art",
            "title": "The Third of May 1808",
            "creator_display_name": "Francisco Goya",
            "image_url": "",
            "description": "A powerful depiction of resistance, execution, and sacrifice during the Peninsular War.",
            "source_type": "manual",
            "source_id": "art_third_of_may_1808",
            "is_user_submitted": False,
            "metadata_confidence": 0.99,
        },
        "metadata": {
            "artist": "Francisco Goya",
            "year": 1814,
            "medium": "Oil on canvas",
            "movement": "Romanticism",
            "museum": "Museo del Prado, Madrid",
        },
    },
    {
        "common": {
            "category": "book",
            "title": "Letter from Birmingham Jail",
            "creator_display_name": "Martin Luther King Jr.",
            "image_url": "",
            "description": "A foundational text of the American civil rights movement defending nonviolent resistance against injustice.",
            "source_type": "manual",
            "source_id": "book_letter_from_birmingham_jail",
            "is_user_submitted": False,
            "metadata_confidence": 0.99,
        },
        "metadata": {
            "author": "Martin Luther King Jr.",
            "year": 1963,
            "pages": 34,
            "publisher": "",
            "isbn": "",
            "language": "English",
        },
    },
]
